module.exports = {
  apps: [
    {
      name: "school-backend",
      cwd: "/home/meriem/llm-project/app/project/backend",
      script: "python3",
      args: "-m uvicorn src.main:app --host 127.0.0.1 --port 8000",
      interpreter: "none",
      exec_mode: "fork",
      instances: 1,
      autorestart: true,
      max_restarts: 10,
      watch: false,
      env: { PYTHONUNBUFFERED: "1" },
      out_file: "/home/meriem/llm-project/app/project/logs/backend.out.log",
      error_file: "/home/meriem/llm-project/app/project/logs/backend.err.log",
      merge_logs: true,
    },
    {
      name: "school-frontend",
      cwd: "/home/meriem/llm-project/app/project/web",
      script: "npm",
      args: "run dev",
      interpreter: "none",
      exec_mode: "fork",
      instances: 1,
      autorestart: true,
      max_restarts: 10,
      watch: false,
      out_file: "/home/meriem/llm-project/app/project/logs/frontend.out.log",
      error_file: "/home/meriem/llm-project/app/project/logs/frontend.err.log",
      merge_logs: true,
    },
    {
      name: "school-tunnel",
      cwd: "/home/meriem/llm-project/app/project",
      script: "cloudflared",
      args: "tunnel --url http://127.0.0.1:5180 --no-autoupdate",
      interpreter: "none",
      exec_mode: "fork",
      instances: 1,
      autorestart: true,
      max_restarts: 5,
      out_file: "/home/meriem/llm-project/app/project/logs/tunnel.out.log",
      error_file: "/home/meriem/llm-project/app/project/logs/tunnel.err.log",
      merge_logs: true,
    },
  ],
};
